version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres-container
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  express:
    build: ./express-app
    container_name: my-express-container
    ports:
      - '3001:3001'
    depends_on:
      - postgres

volumes:
  postgres-data:
